### PR TITLE
Replace gh-pages site with a redirect to viz.hivtrace.org

### PR DESCRIPTION
**Pull request by rdvelazquez**
Shouldn't be merged in until after #41 is merged.

### CODE REVIEW

**Comment by stevenweaver** [comment]
@rdvelazquez, 

We actually own hivtrace.org. We could probably have a nicer url like viz.hivtrace.org. I'm currently using demo.hivtrace.org to redirect to github for two example pages.

Best,
Steven

**Comment by rdvelazquez** [comment]
O nice. I'll move it to viz.hivtrace.org (in this PR as well as in #41). Thanks for the heads up!

**Comment by rdvelazquez** [comment]
@stevenweaver I've now moved the site to viz.hivtrace.org.

**Comment by rdvelazquez** [comment]
@stevenweaver Just as an FYI - I'm waiting to merge this in until #41 has been merged and released. #41 is ready for your review.

**Comment by stevenweaver** [comment]
Hi @rdvelazquez, 

I'm unsure why we would want to move to self-hosting instead of github pages when the app doesn't require a backend. Optimally, we would have a command like `yarn gh-deploy` that would update github automatically. 

Best,
Steven

**Comment by rdvelazquez** [comment]
The benefits I see to self hosting rather than github pages are more control and consistence: we have ~5 sites with no backend that are all hosted using pm2 like our sites that do have a backed. hivtrace-viz is currently the only site that uses github pages rather than pm2.

I know there are some benefits to using github pages but in my mind it's just easier to do everything together with pm2. Just personal preference though, if you think it would be best to keep this site on github pages I don't see an issue with that.

**Pull request closed without merging**
