### PR TITLE
Prettify, refactor bug fixes, and some further refactoring for clusternetwork.js

### PR DESCRIPTION
**Pull request by daniel-ji**
- Various formatting / prettifying of html and js files were done. 
- Removed `dist/` folder (no longer needed since we deploy with Vercel, per @stevenweaver). 

- Previous refactoring changes were quite buggy, my apologies. This PR should have fixes that ensure variables are properly accessible / defined across the new files (that have been created in attempt to modularize up `clusternetwork.js`).

- Various new files have been created, some that may be a bit redundant with already  existing files. Right now, it is a bit disorganized and I've mainly just trying to reduce the size of `clusternetwork.js`, without considering what was the best way to create and organize the code into new files. I was thinking we could deal with consolidating related code in a more organized manner later down the line when `clusternetwork.js` is already reduced. 

- The ClusterOI panel from `clusternetwork.js` is now beginning to be refactored as well.

- I was thinking that with these new files (`src/tables.js`, `src/time_date_util.js`, and `src/utils.js`), to properly set any variables that are used in both `clusternetwork.js` and the particular new file itself (but logically more belonging to the new file), we could create `init` functions that are run in `clusternetwork.js` to set a variable that belongs to the new helper / modularized file and a getter method can be used by `clusternetwork.js` to retrieve its value. Hopefully, in the long run, we would not need the getter method and the variable is self-contained within the new file helper / modularized file. Thoughts? 

- ~~**Question**: Some `dist/` files were modified because of changed `src/` files. This is largely why there is such a high line addition count to this PR. Should I push these? Maybe as a general question overall, should the `dist/` folder be tracked by Git?~~ RESOLVED

- Moving on, I think I'll prioritize creating tests to ensure everything works - finding all these bugs with the previous PR I made seems to be a cautionary tale of what might happen without tests to ensure refactoring doesn't break anything. [Edit: Tests with Playwright are now part of this PR]

Let me know if you all have any questions or concerns. This is a bit of a learning process for me, so I'll definitely try to be more careful next time. Thank you!

### CODE REVIEW

**Comment by stevenweaver** [comment]
> Question: Some dist/ files were modified because of changed src/ files. This is largely why there is such a high line addition count to this PR. Should I push these? Maybe as a general question overall, should the dist/ folder be tracked by Git?

The dist files were included in the repo because it was a pain to manage the `gh-pages` branch back in the day. We don't use that anymore (we've moved to Vercel), so by all means remove.

**Comment by stevenweaver** [comment]
@stephenshank -- I'd rather not revert at this time, please branch from the last release for your work, and we can deal with the issue when it comes time to release.

**Comment by stephenshank** [comment]
@stevenweaver There also was not a Github release of 1.1.6 despite an NPM release and deployment to staging.

I can branch off of a particular commit, but I wasn't sure which one. Can you please confirm that ff4a77954ad48a9e58adb034ad5d89eb9c323476 is the appropriate commit?

FWIW I've expressed interest to @jwertheim in developing CI/CD to trigger NPM releases from Github.

**Comment by stevenweaver** [comment]
Thanks for pointing that out, `yarn` typically creates a commit and tag when publishing, so something went wrong during the process (a situation you will see often if trying to automate publishing with GitHub Actions). That is the correct commit if you want `1.1.6`, but branching off `1.1.5` would have worked fine as well.

**Pull request merged**
