### PR TITLE
Adds badge label views to drop-down menus

### PR DESCRIPTION
**Pull request by stevenweaver**
Also makes attribute schema case-insensitive. 

Screen Shot 2020-02-11 at 11 13 34 AM

### CODE REVIEW

**Comment by spond** [comment]
Ah, this is a nice addition. Do you report the number of unique values for attributes with the badges?

**Comment by stevenweaver** [comment]
Yes, I can add a tool-tip to the badges if that is not clear.

**Comment by spond** [comment]
I think that may not be a bad idea (the tooltip). It was clear to me, but I can't assume what other users might infer.

**Comment by stevenweaver** [comment]
Great, if there aren't any objections, I'd like to merge and release a patch ASAP. This includes a bug fix for Mexico.

**Comment by spond** [comment]
Please do.

**Pull request merged**
