### PR TITLE
Added devcontainer.json and fixed Dockerfile

### PR DESCRIPTION
**Pull request by niemasd**
With this devcontainer file, VS Code (and GitHub Codespaces) will be able to create the development environment automatically. I also fixed the `yarn` installation in the `Dockerfile`.

### CODE REVIEW

**Comment by niemasd** [comment]
Actually, there are some more fixes that need to be made to the `Dockerfile`, so don't merge this specific PR yet. The `tn93` and `hivtrace` ones should be good to go, though

**Comment by niemasd** [comment]
I've ported the Dockerfile to use Oracle Linux instead of Ubuntu, and I'm now stuck at the same place as I was in Ubuntu:

https://github.com/veg/hivtrace-viz/issues/118#issuecomment-1808753760

@stevenweaver Thoughts?

**Comment by stevenweaver** [comment]
I've updated the supported engines to `18` and `19` until underlying dependencies can be updated to support Node 20 and above in earnest.

**Comment by niemasd** [comment]
@stevenweaver Great, thanks for the info! Switching to Node 18 worked perfectly. As of the following commit:

https://github.com/veg/hivtrace-viz/pull/119/commits/65db7052fc55871fd748e6bab42919ad2d35702d

I'm able to build directly from the development environment with the following:

```bash
yarn
yarn develop # or yarn build
```

So this one should be good to go now! In GitHub Codespaces, I'm even able to load the deployed web app

**Comment by stevenweaver** [comment]
Many thanks @niemasd.

**Pull request merged**
